### PR TITLE
Withdraw + flashloan permissions

### PR DESCRIPTION
**Pull request by emilianobonassi**
Beautiful starter, congrats @mrdavey !

Few additions from my flashloan projects as you suggested to be ready for mainnet

- Add `withdraw` function to recover funds
- Add a modifier `onlyOwner` to `flashloan` function
- Few stuff for developer experience (ignore artifact folder, add truffle as devdep)

### CODE REVIEW

**Comment by mrdavey** [comment]
This is great @emilianobonassi .

One of the reasons why I included the OpenZeppelin files individually (instead of importing them from git) was to make it easier for beginners to copy+paste the entire directory and run it however they wanted (i.e. via Remix if they wanted).

I think this PR will break that feature right? Is there a way to make it easily copy+pasteable to an IDE like Remix and have it import all the correct contracts?

**Comment by sakulstra** [comment]
Chiming in with an experience here :sweat_smile:

I'm a real beginner in regards to sol and all these smart-contract things and I learned a lot, but just reading your readme and playing around with the repo (thx for that :+1:)

---

I feel to make any reasonable use of flashloans you have to interact with some protocols eventually so you won't get around learning how these things work(as they are likely to ship their stuff via npm) - so i'd personally prefer the node_modules approach and a link in the readme to read up on how to deploy this.

**Comment by mrdavey** [comment]
Sorry for the slowness. I've had a think about this and agree, it's a good way to go about it as this template requires the dev to install and use Truffle anyway.

**Comment by emilianobonassi** [comment]
@mrdavey you don't need to sorry, I appreciated that you take the time to think more, it's better a slow right decision that a fast not so right one 👍

Thanks @sakulstra for your opinion, IMHO it was essential to understand what's the feedback of a potential user of this repo!

I am willing to go ahead with other improvements and sharing 😎

**Pull request merged**
